export default {
    ADD_ERROR: 'ADD_ERROR',
    CLEAR_ERRORS: 'CLEAR_ERRORS',
    GET_USERS: 'GET_USERS',
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    REMOVE_ERROR: 'REMOVE_ERROR',
    SET_USER_ROLE: 'SET_USER_ROLE',
    SET_USER_ROLE_SUCCESS: 'SET_USER_ROLE_SUCCESS',
    SIGN_IN: 'SIGN_IN',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_OUT: 'SIGN_OUT',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_UP: 'SIGN_UP',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    UPDATE_PROFILE: 'UPDATE_PROFILE',
    UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
    UPDATE_SETTINGS: 'UPDATE_SETTINGS',
    UPDATE_SETTINGS_SUCCESS: 'UPDATE_SETTINGS_SUCCESS'
};
