export default {
    NOTIFICATIONS: {
        ADD_NOTIFICATION: 'ADD_ERROR',
        CLEAR_NOTIFICATION: 'CLEAR_ERRORS',
        REMOVE_NOTIFICATION: 'REMOVE_ERROR'
    },
    SESSION: {
        CLOSE_PROFILE: 'CLOSE_PROFILE',
        CLOSE_PROFILE_SUCCESS: 'CLOSE_PROFILE_SUCCESS',
        GET_SETTINGS: 'GET_SETTINGS',
        GET_SETTINGS_SUCCESS: 'GET_SETTINGS_SUCCESS',
        SIGN_IN: 'SIGN_IN',
        SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
        SIGN_OUT: 'SIGN_OUT',
        SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
        SIGN_UP: 'SIGN_UP',
        SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
        UPDATE_PROFILE: 'UPDATE_PROFILE',
        UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
        UPDATE_SETTINGS: 'UPDATE_SETTINGS',
        UPDATE_SETTINGS_SUCCESS: 'UPDATE_SETTINGS_SUCCESS'
    },
    USERS: {
        GET_USERS: 'GET_USERS',
        GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
        SET_USER_ROLE: 'SET_USER_ROLE',
        SET_USER_ROLE_SUCCESS: 'SET_USER_ROLE_SUCCESS'
    }
};
